apiVersion: v1
kind: Service
metadata:
  name: clientes-service
  labels:
    app: clientes
spec:
  selector:
    app: clientes
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      # NodePort deve ser um valor entre 30000-32767 (opcional deixar o Kubernetes escolher)
      nodePort: 32082
  type: NodePort
