apiVersion: v1
kind: Service
metadata:
  name: clientes-service
  labels:
    app: clientes
spec:
  selector:
    app: clientes
  ports:
    - name: http
      port: 8082        # porta do serviço no cluster
      targetPort: 8082  # porta exposta pelo container
  type: NodePort        # expõe externamente (para acessar pelo Play with Kubernetes)
